# This file was generated by GoReleaser. DO NOT EDIT.
cask "work" do
  name "work"
  desc "Claude Code worktree manager — parallel AI coding sessions"
  homepage "https://github.com/tSquaredd/work-cli"
  version "0.5.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "work"

  on_macos do
    on_intel do
      url "https://github.com/tSquaredd/work-cli/releases/download/v#{version}/work_darwin_amd64.tar.gz"
      sha256 "0e86d270af55cceee41f4fd5a181754ec629af9897b425e07cf61d19b1de5bce"
    end
    on_arm do
      url "https://github.com/tSquaredd/work-cli/releases/download/v#{version}/work_darwin_arm64.tar.gz"
      sha256 "f94412fd43a82a2877f93e088f8551d34fab85994846e44c9042dc540fcfb3af"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/tSquaredd/work-cli/releases/download/v#{version}/work_linux_amd64.tar.gz"
      sha256 "308e007f8cce643484aa041a96d1a73a368dc1be4cc3d44e3c7caa1ca71cf8a6"
    end
    on_arm do
      url "https://github.com/tSquaredd/work-cli/releases/download/v#{version}/work_linux_arm64.tar.gz"
      sha256 "6323ca4eb9031362ccdede3e6d52c54a4a4b7b9743bdeae03b03f6ffb74efa41"
    end
  end

  # No zap stanza required
end
