# This file was generated by GoReleaser. DO NOT EDIT.
cask "work" do
  name "work"
  desc "Claude Code worktree manager — parallel AI coding sessions"
  homepage "https://github.com/tSquaredd/work-cli"
  version "0.5.19"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "work"

  on_macos do
    on_intel do
      url "https://github.com/tSquaredd/work-cli/releases/download/v#{version}/work_darwin_amd64.tar.gz"
      sha256 "e83e24ec667233088a5990331707042754f3940868c446ed423b180c6cd8d75a"
    end
    on_arm do
      url "https://github.com/tSquaredd/work-cli/releases/download/v#{version}/work_darwin_arm64.tar.gz"
      sha256 "366862ed7e946c49782f55d735ee69f8c0440c27dbf94e566224c17df9be5fa5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/tSquaredd/work-cli/releases/download/v#{version}/work_linux_amd64.tar.gz"
      sha256 "94e5016a9d5fcd6475739d62a107cbd144461897dfd333818db0d8e00e17ac98"
    end
    on_arm do
      url "https://github.com/tSquaredd/work-cli/releases/download/v#{version}/work_linux_arm64.tar.gz"
      sha256 "ce812114838c36ab433b6774356e3fc4d342e891f0a0e9b460c70ce9914612b7"
    end
  end

  # No zap stanza required
end
